/**
 * @NApiVersion 2.x
 * @NScriptType WorkflowActionScript
 */
 define(['N/search', 'N/record'], function (search, record) {
    // var countryByCodes = {
    //     "Canada": "CA",
    //     "United States": "US",
    //     "Andorra": "AD",
    //     "Austria": "AT",
    //     "Belgium": "BE",
    //     "Bulgaria": "BG",
    //     "Croatia": "HR",
    //     "Czech Republic": "CZ",
    //     "Cyprus": "CY",
    //     "Denmark": "DK",
    //     "Estonia": "EE",
    //     "Finland": "FI",
    //     "France": "FR",
    //     "Germany": "DE",
    //     "Greece": "GR",
    //     "Hungary": "HU",
    //     "Iceland": "IS",
    //     "Ireland": "IE",
    //     "Italy": "IT",
    //     "Jersey": "JE",
    //     "Latvia": "LV",
    //     "Lithuania": "LT",
    //     "Liechtenstein": "LI",
    //     "Luxembourg": "LU",
    //     "Malta": "MT",
    //     "Monaco": "MC",
    //     "Netherlands": "NL",
    //     "Norway": "NO",
    //     "Poland": "PL",
    //     "Portugal (incl. Azoresand Madeira)": "PT",
    //     "Romania": "RO",
    //     "San Marino": "SM",
    //     "Slovakia": "SK",
    //     "Slovenia": "SI",
    //     "Spain": "ES",
    //     "Sweden": "SE",
    //     "Switzerland": "CH",
    //     "United Kingdom": "GB",
    //     "Vatican City": "VA",
    //     "Keny": "KE"
    // };
    var countryByCodes = {
        "Afghanistan": "AF",
        "Aland Islands": "AX",
        "Albania": "AL",
        "Algeria": "DZ",
        "American Samoa": "AS",
        "Andorra": "AD",
        "Angola": "AO",
        "Anguilla": "AI",
        "Antarctica": "AQ",
        "Antigua and Barbuda": "AG",
        "Argentina": "AR",
        "Armenia": "AM",
        "Aruba": "AW",
        "Australia": "AU",
        "Austria": "AT",
        "Azerbaijan": "AZ",
        "Bahamas": "BS",
        "Bahrain": "BH",
        "Bangladesh": "BD",
        "Barbados": "BB",
        "Belarus": "BY",
        "Belgium": "BE",
        "Belize": "BZ",
        "Benin": "BJ",
        "Bermuda": "BM",
        "Bhutan": "BT",
        "Bolivia": "BO",
        "Bonaire Saint Eustatius and Saba": "BQ",
        "Bosnia and Herzegovina": "BA",
        "Botswana": "BW",
        "Bouvet Island": "BV",
        "Brazil": "BR",
        "British Indian Ocean Territory": "IO",
        "Brunei Darussalam": "BN",
        "Bulgaria": "BG",
        "Burkina Faso": "BF",
        "Burundi": "BI",
        "Cambodia": "KH",
        "Cameroon": "CM",
        "Canada": "CA",
        "Canary Islands": "IC",
        "Cape Verde": "CV",
        "Cayman Islands": "KY",
        "Central African Republic": "CF",
        "Ceuta and Melilla": "EA",
        "Chad": "TD",
        "Chile": "CL",
        "China": "CN",
        "Christmas Island": "CX",
        "Cocos (Keeling) Islands": "CC",
        "Colombia": "CO",
        "Comoros": "KM",
        "Congo Democratic Republic of": "CD",
        "Congo Republic of": "CG",
        "Cook Islands": "CK",
        "Costa Rica": "CR",
        "Cote d'Ivoire": "CI",
        "Croatia/Hrvatska": "HR",
        "Cuba": "CU",
        "Curaçao": "CW",
        "Cyprus": "CY",
        "Czech Republic": "CZ",
        "Denmark": "DK",
        "Djibouti": "DJ",
        "Dominica": "DM",
        "Dominican Republic": "DO",
        "East Timor": "TL",
        "Ecuador": "EC",
        "Egypt": "EG",
        "El Salvador": "SV",
        "Equatorial Guinea": "GQ",
        "Eritrea": "ER",
        "Estonia": "EE",
        "Ethiopia": "ET",
        "Falkland Islands": "FK",
        "Faroe Islands": "FO",
        "Fiji": "FJ",
        "Finland": "FI",
        "France": "FR",
        "French Guiana": "GF",
        "French Polynesia": "PF",
        "French Southern Territories": "TF",
        "Gabon": "GA",
        "Gambia": "GM",
        "Georgia": "GE",
        "Germany": "DE",
        "Ghana": "GH",
        "Gibraltar": "GI",
        "Greece": "GR",
        "Greenland": "GL",
        "Grenada": "GD",
        "Guadeloupe": "GP",
        "Guam": "GU",
        "Guatemala": "GT",
        "Guernsey": "GG",
        "Guinea": "GN",
        "Guinea-Bissau": "GW",
        "Guyana": "GY",
        "Haiti": "HT",
        "Heard and McDonald Islands": "HM",
        "Holy See (City Vatican State)": "VA",
        "Honduras": "HN",
        "Hong Kong": "HK",
        "Hungary": "HU",
        "Iceland": "IS",
        "India": "IN",
        "Indonesia": "ID",
        "Iran (Islamic Republic of)": "IR",
        "Iraq": "IQ",
        "Ireland": "IE",
        "Isle of Man": "IM",
        "Israel": "IL",
        "Italy": "IT",
        "Jamaica": "JM",
        "Japan": "JP",
        "Jersey": "JE",
        "Jordan": "JO",
        "Kazakhstan": "KZ",
        "Kenya": "KE",
        "Kiribati": "KI",
        "Korea Democratic People's Republic": "KP",
        "Korea Republic of": "KR",
        "Kosovo": "XK",
        "Kuwait": "KW",
        "Kyrgyzstan": "KG",
        "Lao People's Democratic Republic": "LA",
        "Latvia": "LV",
        "Lebanon": "LB",
        "Lesotho": "LS",
        "Liberia": "LR",
        "Libya": "LY",
        "Liechtenstein": "LI",
        "Lithuania": "LT",
        "Luxembourg": "LU",
        "Macau": "MO",
        "Macedonia": "MK",
        "Madagascar": "MG",
        "Malawi": "MW",
        "Malaysia": "MY",
        "Maldives": "MV",
        "Mali": "ML",
        "Malta": "MT",
        "Marshall Islands": "MH",
        "Martinique": "MQ",
        "Mauritania": "MR",
        "Mauritius": "MU",
        "Mayotte": "YT",
        "Mexico": "MX",
        "Micronesia Federal State of": "FM",
        "Moldova Republic of": "MD",
        "Monaco": "MC",
        "Mongolia": "MN",
        "Montenegro": "ME",
        "Montserrat": "MS",
        "Morocco": "MA",
        "Mozambique": "MZ",
        "Myanmar (Burma)": "MM",
        "Namibia": "NA",
        "Nauru": "NR",
        "Nepal": "NP",
        "Netherlands": "NL",
        "Netherlands Antilles (Deprecated)": "AN",
        "New Caledonia": "NC",
        "New Zealand": "NZ",
        "Nicaragua": "NI",
        "Niger": "NE",
        "Nigeria": "NG",
        "Niue": "NU",
        "Norfolk Island": "NF",
        "Northern Mariana Islands": "MP",
        "Norway": "NO",
        "Oman": "OM",
        "Pakistan": "PK",
        "Palau": "PW",
        "Panama": "PA",
        "Papua New Guinea": "PG",
        "Paraguay": "PY",
        "Peru": "PE",
        "Philippines": "PH",
        "Pitcairn Island": "PN",
        "Poland": "PL",
        "Portugal": "PT",
        "Puerto Rico": "PR",
        "Qatar": "QA",
        "Reunion Island": "RE",
        "Romania": "RO",
        "Russian Federation": "RU",
        "Rwanda": "RW",
        "Saint Barthélemy": "BL",
        "Saint Helena": "SH",
        "Saint Kitts and Nevis": "KN",
        "Saint Lucia": "LC",
        "Saint Martin": "MF",
        "Saint Vincent and the Grenadines": "VC",
        "Samoa": "WS",
        "San Marino": "SM",
        "Sao Tome and Principe": "ST",
        "Saudi Arabia": "SA",
        "Senegal": "SN",
        "Serbia": "RS",
        "Serbia and Montenegro (Deprecated)": "CS",
        "Seychelles": "SC",
        "Sierra Leone": "SL",
        "Singapore": "SG",
        "Sint Maarten": "SX",
        "Slovak Republic": "SK",
        "Slovenia": "SI",
        "Solomon Islands": "SB",
        "Somalia": "SO",
        "South Africa": "ZA",
        "South Georgia": "GS",
        "South Sudan": "SS",
        "Spain": "ES",
        "Sri Lanka": "LK",
        "St. Pierre and Miquelon": "PM",
        "State of Palestine": "PS",
        "Sudan": "SD",
        "Suriname": "SR",
        "Svalbard and Jan Mayen Islands": "SJ",
        "Swaziland": "SZ",
        "Sweden": "SE",
        "Switzerland": "CH",
        "Syrian Arab Republic": "SY",
        "Taiwan": "TW",
        "Tajikistan": "TJ",
        "Tanzania": "TZ",
        "Thailand": "TH",
        "Togo": "TG",
        "Tokelau": "TK",
        "Tonga": "TO",
        "Trinidad and Tobago": "TT",
        "Tunisia": "TN",
        "Turkey": "TR",
        "Turkmenistan": "TM",
        "Turks and Caicos Islands": "TC",
        "Tuvalu": "TV",
        "Uganda": "UG",
        "Ukraine": "UA",
        "United Arab Emirates": "AE",
        "United Kingdom": "GB",
        "United States": "US",
        "Uruguay": "UY",
        "US Minor Outlying Islands": "UM",
        "Uzbekistan": "UZ",
        "Vanuatu": "VU",
        "Venezuela": "VE",
        "Vietnam": "VN",
        "Virgin Islands (British)": "VG",
        "Virgin Islands (USA)": "VI",
        "Wallis and Futuna": "WF",
        "Western Sahara": "EH",
        "Yemen": "YE",
        "Zambia": "ZM",
        "Zimbabwe": "ZW"
    };
    var currencyByCodes = {
        "ADB Unit of Account": "XUA",
        "Afghani": "AFN",
        "Algerian Dinar": "DZD",
        "Argentine Peso": "ARS",
        "Armenian Dram": "AMD",
        "Aruban Florin": "AWG",
        "Australian Dollar": "AUD",
        "Azerbaijan Manat": "AZN",
        "Bahamian Dollar": "BSD",
        "Bahraini Dinar": "BHD",
        "Baht": "THB",
        "Balboa": "PAB",
        "Barbados Dollar": "BBD",
        "Belarusian Ruble": "BYN",
        "Belize Dollar": "BZD",
        "Bermudian Dollar": "BMD",
        "Boliviano": "BOB",
        "Bolívar Soberano": "VES",
        "Brazilian Real": "BRL",
        "Brunei Dollar": "BND",
        "Bulgarian Lev": "BGN",
        "Burundi Franc": "BIF",
        "CFA Franc BCEAO": "XOF",
        "CFA Franc BEAC": "XAF",
        "CFP Franc": "XPF",
        "Cabo Verde Escudo": "CVE",
        "Canadian Dollar": "CAD",
        "Cayman Islands Dollar": "KYD",
        "Chilean Peso": "CLP",
        "Colombian Peso": "COP",
        "Comorian Franc ": "KMF",
        "Congolese Franc": "CDF",
        "Convertible Mark": "BAM",
        "Cordoba Oro": "NIO",
        "Costa Rican Colon": "CRC",
        "Cuban Peso": "CUP",
        "Czech Koruna": "CZK",
        "Dalasi": "GMD",
        "Danish Krone": "DKK",
        "Denar": "MKD",
        "Djibouti Franc": "DJF",
        "Dobra": "STN",
        "Dominican Peso": "DOP",
        "Dong": "VND",
        "East Caribbean Dollar": "XCD",
        "Egyptian Pound": "EGP",
        "El Salvador Colon": "SVC",
        "Ethiopian Birr": "ETB",
        "Euro": "EUR",
        "Falkland Islands Pound": "FKP",
        "Fiji Dollar": "FJD",
        "Forint": "HUF",
        "Ghana Cedi": "GHS",
        "Gibraltar Pound": "GIP",
        "Gourde": "HTG",
        "Guarani": "PYG",
        "Guinean Franc": "GNF",
        "Guyana Dollar": "GYD",
        "Hong Kong Dollar": "HKD",
        "Hryvnia": "UAH",
        "Iceland Krona": "ISK",
        "Indian Rupee": "INR",
        "Iranian Rial": "IRR",
        "Iraqi Dinar": "IQD",
        "Jamaican Dollar": "JMD",
        "Jordanian Dinar": "JOD",
        "Kenyan Shilling": "KES",
        "Kina": "PGK",
        "Kuna": "HRK",
        "Kuwaiti Dinar": "KWD",
        "Kwanza": "AOA",
        "Kyat": "MMK",
        "Lao Kip": "LAK",
        "Lari": "GEL",
        "Lebanese Pound": "LBP",
        "Lek": "ALL",
        "Lempira": "HNL",
        "Leone": "SLL",
        "Leone": "SLE",
        "Liberian Dollar": "LRD",
        "Libyan Dinar": "LYD",
        "Lilangeni": "SZL",
        "Loti": "LSL",
        "Malagasy Ariary": "MGA",
        "Malawi Kwacha": "MWK",
        "Malaysian Ringgit": "MYR",
        "Mauritius Rupee": "MUR",
        "Mexican Peso": "MXN",
        "Mexican Unidad de Inversion (UDI)": "MXV",
        "Moldovan Leu": "MDL",
        "Moroccan Dirham": "MAD",
        "Moroccan Dirham": "MAD",
        "Mozambique Metical": "MZN",
        "Mvdol": "BOV",
        "Naira": "NGN",
        "Nakfa": "ERN",
        "Namibia Dollar": "NAD",
        "Nepalese Rupee": "NPR",
        "Netherlands Antillean Guilder": "ANG",
        "New Israeli Sheqel": "ILS",
        "New Taiwan Dollar": "TWD",
        "New Zealand Dollar": "NZD",
        "Ngultrum": "BTN",
        "North Korean Won": "KPW",
        "Norwegian Krone": "NOK",
        "Ouguiya": "MRU",
        "Pakistan Rupee": "PKR",
        "Pataca": "MOP",
        "Pa’anga": "TOP",
        "Peso Convertible": "CUC",
        "Peso Uruguayo": "UYU",
        "Philippine Peso": "PHP",
        "Pound Sterling": "GBP",
        "British Pound": "GBP",
        "Pula": "BWP",
        "Qatari Rial": "QAR",
        "Quetzal": "GTQ",
        "Rand": "ZAR",
        "Rial Omani": "OMR",
        "Riel": "KHR",
        "Romanian Leu": "RON",
        "Rufiyaa": "MVR",
        "Rupiah": "IDR",
        "Russian Ruble": "RUB",
        "Rwanda Franc": "RWF",
        "SDR (Special Drawing Right)": "XDR",
        "Saint Helena Pound": "SHP",
        "Saudi Riyal": "SAR",
        "Serbian Dinar": "RSD",
        "Seychelles Rupee": "SCR",
        "Singapore Dollar": "SGD",
        "Sol": "PEN",
        "Solomon Islands Dollar": "SBD",
        "Som": "KGS",
        "Somali Shilling": "SOS",
        "Somoni": "TJS",
        "South Sudanese Pound": "SSP",
        "Sri Lanka Rupee": "LKR",
        "Sucre": "XSU",
        "Sudanese Pound": "SDG",
        "Surinam Dollar": "SRD",
        "Swedish Krona": "SEK",
        "Swedish Kronor": "SEK",
        "Swiss Franc": "CHF",
        "Syrian Pound": "SYP",
        "Taka": "BDT",
        "Tala": "WST",
        "Tanzanian Shilling": "TZS",
        "Tenge": "KZT",
        "Trinidad and Tobago Dollar": "TTD",
        "Tugrik": "MNT",
        "Tunisian Dinar": "TND",
        "Turkish Lira": "TRY",
        "Turkmenistan New Manat": "TMT",
        "UAE Dirham": "AED",
        "US Dollar": "USD",
        "US Dollar (Next day)": "USN",
        "Uganda Shilling": "UGX",
        "Unidad Previsional": "UYW",
        "Unidad de Fomento": "CLF",
        "Unidad de Valor Real": "COU",
        "Uruguay Peso en Unidades Indexadas (UI)": "UYI",
        "Uzbekistan Sum": "UZS",
        "Vatu": "VUV",
        "WIR Euro": "CHE",
        "WIR Franc": "CHW",
        "Won": "KRW",
        "South Korean Won": "KRW",
        "Yemeni Rial": "YER",
        "Yen": "JPY",
        "Japan Yen": "JPY",
        "Yuan Renminbi": "CNY",
        "Renminbi": "CNY",
        "Zambian Kwacha": "ZMW",
        "Zimbabwe Dollar": "ZWL",
        "Zloty": "PLN"
    };
    function onAction(scriptContext) {
        var newRecord = scriptContext.newRecord;
        var name = newRecord.getValue('name'),
            vendor = newRecord.getValue('custrecord_2663_parent_vendor'),
            country = newRecord.getText('custrecord_2663_entity_country'),
            currency = newRecord.getText('custrecord_hf_currency_code'),
            method = newRecord.getText('custrecord_hf_method'),
            accountNumber = newRecord.getValue('custrecord_2663_entity_acct_no'),
            bankRoutingNumber = newRecord.getValue('custrecord_2663_entity_bank_no'),
            bankAccountType = newRecord.getText('custrecord_2663_entity_bank_acct_type');
		if(countryByCodes.hasOwnProperty(country)){
            country = countryByCodes[country];
        }
        if(currencyByCodes.hasOwnProperty(currency)){
            currency = currencyByCodes[currency];
        }
        var customrecord_fispan_vendor_bank_detailsSearchObj = search.create({
            type: "customrecord_fispan_vendor_bank_details",
            filters:
                [
                    ["custrecord_fispan_vbd_vendor", "anyof", vendor],
                    "AND",
                    ["isinactive", "is", "F"]
                ],
            columns:
                [
                    search.createColumn({
                        name: "name",
                        sort: search.Sort.ASC
                    }),
                    search.createColumn({ name: "internalid", label: "Internal ID" })
                ]
        });
        var searchResultCount = customrecord_fispan_vendor_bank_detailsSearchObj.runPaged().count;
        log.debug('searchResultCount', searchResultCount);
        if (searchResultCount > 0) {
            updateVendorBank(customrecord_fispan_vendor_bank_detailsSearchObj, vendor, country, currency, bankAccountType, accountNumber, bankRoutingNumber, name, method);
        } else {
            createVendorBank(vendor, country, currency, bankAccountType, accountNumber, bankRoutingNumber, name, method);
        }
        return 1;
    }
    function updateVendorBank(customrecord_fispan_vendor_bank_detailsSearchObj, vendor, country, currency, bankAccountType, accountNumber, bankRoutingNumber, name, method) {
        log.debug('updateVendorBank', vendor);
        var recId;
        customrecord_fispan_vendor_bank_detailsSearchObj.run().each(function (result) {
            recId = result.getValue('internalid');
            return false;
        });
        var vendorData = record.load({ type: 'customrecord_fispan_vendor_bank_details', id: recId });

        vendorData.setValue('custrecord_fispan_vbd_vendor', vendor);
        vendorData.setValue('custrecord_fispan_vbd_country', country);
        vendorData.setValue('custrecord_fispan_vbd_currency', currency);
        vendorData.setValue('custrecord_fispan_vbd_method', method.toUpperCase());

        var paymentData = {};
        paymentData.accountType = bankAccountType.toUpperCase();
        paymentData.accountNumber = accountNumber;
        paymentData.routingNumber = bankRoutingNumber;

        vendorData.setValue('custrecord_fispan_vbd_primary', true);
        vendorData.setValue('custrecord_fispan_vbd_label', name);
        vendorData.setValue('custrecord_fispan_vbd_payment_data', JSON.stringify(paymentData));
        vendorData.setValue('name', name);

        var vendorId = vendorData.save();

        log.debug('vendorId', vendorId);
    }
    function createVendorBank(vendor, country, currency, bankAccountType, accountNumber, bankRoutingNumber, name, method) {
        log.debug('createVendorBank', vendor);
        var vendorData = record.create({ type: 'customrecord_fispan_vendor_bank_details' });

        vendorData.setValue('custrecord_fispan_vbd_vendor', vendor);
        vendorData.setValue('custrecord_fispan_vbd_country', country);
        vendorData.setValue('custrecord_fispan_vbd_currency', currency);
        vendorData.setValue('custrecord_fispan_vbd_method', method.toUpperCase());

        var paymentData = {};
        paymentData.accountType = bankAccountType.toUpperCase();
        paymentData.accountNumber = accountNumber;
        paymentData.routingNumber = bankRoutingNumber;

        vendorData.setValue('custrecord_fispan_vbd_primary', true);
        vendorData.setValue('custrecord_fispan_vbd_label', name);
        vendorData.setValue('custrecord_fispan_vbd_payment_data', JSON.stringify(paymentData));
        vendorData.setValue('name', name);

        var vendorId = vendorData.save();
        log.debug('vendorData', vendorData);
    }
    return {
        onAction: onAction
    }
});